spring.application.name=CxApplication
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/db_cx
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
security.jwt.key.private=123

# ========== JPA/HIBERNATE (ostgreSQL) ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota